name: Java CI with Maven
on:
  pull_request:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    - name: Spotless Check
      run: ./gradlew spotlessCheck
    - name: Test with coverage
      run: ./gradlew test jacocoTestReport jacocoTestCoverageVerification
    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: build/reports/jacoco/test/html
    - name: Test
      run: ./gradlew build
      
